version: "3.1"
name: "jfilipedias"

services:
  db:
    image: postgres:16.1-alpine3.19
    environment:
      - POSTGRES_USER=local_user
      - POSTGRES_PASSWORD=local_password
      - POSTGRES_DB=local_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "340MB"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U local_user -d local_db'"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
